jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.6.7.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-hightide-8.1.3.v20120416.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.5.jar"
http_port: 9080
https_port: 9443
max_concurrent_connections: 15
java_options: -Xmx256M
keystore: "etc/fake.p12"
keystore_password: "foobar"
