java: "java"
jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.7.25.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-distribution-9.2.18.v20160721.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.20.jar"
http_port: 9080
https_port: 9443
max_threads: 50
java_options: -Xmx256M
keystore: "etc/fake.p12"
keystore_password: "foobar"
truststore: "etc/fake.p12"
truststore_password: "foobar"
