jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.7.3.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-hightide-8.1.8.v20121106.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.13.1.jar"
http_port: 9080
https_port: 9443
max_concurrent_connections: 15
java_options: -Xmx256M
keystore: "etc/fake.p12"
keystore_password: "foobar"
