jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.7.25.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-distribution-9.2.9.v20150224.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.18.jar"
http_port: 20080
https_port: 20443
ruby_version: 1.9
app_type: rack
keystore: "etc/fake.p12"
keystore_password: "foobar"
truststore: "etc/fake.p12"
truststore_password: "foobar"
